AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: nodejs6.10
    CodeUri: .
    Environment:
      Variables:
        ATHENA_CLIENT_ID: 
        ATHENA_CLIENT_SECRET:
        ATHENA_PRACTICE_ID:
Resources:
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Events:
        DefaultHandler:
          Type: Api
          Properties:
            Path: /
            Method: get
